var hierarchy =
[
    [ "AccountNotActive", "class_account_not_active.html", null ],
    [ "BadDate", "class_bad_date.html", null ],
    [ "BadFile", "class_bad_file.html", null ],
    [ "BinaryNode< Comparable >", "class_binary_node.html", null ],
    [ "BinaryNode< Donate >", "class_binary_node.html", null ],
    [ "BST< Comparable >", "class_b_s_t.html", null ],
    [ "BST< Donate >", "class_b_s_t.html", null ],
    [ "BSTItrIn< Comparable >", "class_b_s_t_itr_in.html", null ],
    [ "BSTItrLevel< Comparable >", "class_b_s_t_itr_level.html", null ],
    [ "BSTItrPost< Comparable >", "class_b_s_t_itr_post.html", null ],
    [ "BSTItrPre< Comparable >", "class_b_s_t_itr_pre.html", null ],
    [ "Date", "class_date.html", null ],
    [ "Donate", "class_donate.html", null ],
    [ "InvalidDonationValue", "class_invalid_donation_value.html", null ],
    [ "InvalidEvaluation", "class_invalid_evaluation.html", null ],
    [ "iteratorBST< Comparable >", "classiterator_b_s_t.html", null ],
    [ "NickIsTaken", "class_nick_is_taken.html", null ],
    [ "NoStreamsFound", "class_no_streams_found.html", null ],
    [ "NotInRange", "class_not_in_range.html", null ],
    [ "NotInWhitelist", "class_not_in_whitelist.html", null ],
    [ "NotNumber", "class_not_number.html", null ],
    [ "PrivateStreamFull", "class_private_stream_full.html", null ],
    [ "PurchaseOrder", "class_purchase_order.html", null ],
    [ "StockNotEnough", "class_stock_not_enough.html", null ],
    [ "Stream", "class_stream.html", [
      [ "PrivateStream", "class_private_stream.html", null ]
    ] ],
    [ "StreamerAlreadyStreaming", "class_streamer_already_streaming.html", null ],
    [ "StreamerNotStreaming", "class_streamer_not_streaming.html", null ],
    [ "StreamerTooYoung", "class_streamer_too_young.html", null ],
    [ "StreamNotPrivate", "class_stream_not_private.html", null ],
    [ "StreamZ", "class_stream_z.html", null ],
    [ "TooYoungForStream", "class_too_young_for_stream.html", null ],
    [ "User", "class_user.html", [
      [ "Admin", "class_admin.html", null ],
      [ "Streamer", "class_streamer.html", null ],
      [ "Viewer", "class_viewer.html", null ]
    ] ],
    [ "UserHash< U >", "class_user_hash.html", null ],
    [ "UserHash< Admin >", "class_user_hash.html", null ],
    [ "UserHash< Streamer >", "class_user_hash.html", null ],
    [ "UserHash< Viewer >", "class_user_hash.html", null ],
    [ "UserNotFound", "class_user_not_found.html", null ],
    [ "ViewerAlreadyWatching", "class_viewer_already_watching.html", null ],
    [ "ViewerNotWatching", "class_viewer_not_watching.html", null ],
    [ "ViewerTooYoung", "class_viewer_too_young.html", null ]
];